/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiChatRouteImport } from './routes/api/chat'
import { Route as ApiAnalyzeRouteImport } from './routes/api/analyze'
import { Route as ApiVoiceTtsRouteImport } from './routes/api/voice/tts'
import { Route as ApiVoiceCloneRouteImport } from './routes/api/voice/clone'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAnalyzeRoute = ApiAnalyzeRouteImport.update({
  id: '/api/analyze',
  path: '/api/analyze',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiVoiceTtsRoute = ApiVoiceTtsRouteImport.update({
  id: '/api/voice/tts',
  path: '/api/voice/tts',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiVoiceCloneRoute = ApiVoiceCloneRouteImport.update({
  id: '/api/voice/clone',
  path: '/api/voice/clone',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/api/analyze': typeof ApiAnalyzeRoute
  '/api/chat': typeof ApiChatRoute
  '/api/voice/clone': typeof ApiVoiceCloneRoute
  '/api/voice/tts': typeof ApiVoiceTtsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/api/analyze': typeof ApiAnalyzeRoute
  '/api/chat': typeof ApiChatRoute
  '/api/voice/clone': typeof ApiVoiceCloneRoute
  '/api/voice/tts': typeof ApiVoiceTtsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/api/analyze': typeof ApiAnalyzeRoute
  '/api/chat': typeof ApiChatRoute
  '/api/voice/clone': typeof ApiVoiceCloneRoute
  '/api/voice/tts': typeof ApiVoiceTtsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/api/analyze'
    | '/api/chat'
    | '/api/voice/clone'
    | '/api/voice/tts'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/api/analyze'
    | '/api/chat'
    | '/api/voice/clone'
    | '/api/voice/tts'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/api/analyze'
    | '/api/chat'
    | '/api/voice/clone'
    | '/api/voice/tts'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  ApiAnalyzeRoute: typeof ApiAnalyzeRoute
  ApiChatRoute: typeof ApiChatRoute
  ApiVoiceCloneRoute: typeof ApiVoiceCloneRoute
  ApiVoiceTtsRoute: typeof ApiVoiceTtsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/analyze': {
      id: '/api/analyze'
      path: '/api/analyze'
      fullPath: '/api/analyze'
      preLoaderRoute: typeof ApiAnalyzeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/voice/tts': {
      id: '/api/voice/tts'
      path: '/api/voice/tts'
      fullPath: '/api/voice/tts'
      preLoaderRoute: typeof ApiVoiceTtsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/voice/clone': {
      id: '/api/voice/clone'
      path: '/api/voice/clone'
      fullPath: '/api/voice/clone'
      preLoaderRoute: typeof ApiVoiceCloneRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  ApiAnalyzeRoute: ApiAnalyzeRoute,
  ApiChatRoute: ApiChatRoute,
  ApiVoiceCloneRoute: ApiVoiceCloneRoute,
  ApiVoiceTtsRoute: ApiVoiceTtsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
